export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  UPDATE_BASKET_ITEM: "UPDATE_BASKET_ITEM",
  CLEAR_BASKET: "CLEAR_BASKET",
  SET_USER: "SET_USER",
  EMPTY_BASKET: "EMPTY_BASKET",
};
